import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import CursorFollower from "@/components/cursor-follower";
import { Footer } from "@/components/footer";
import { ScrollToTopButton } from "@/components/ScrollToTopButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange>
          <NextIntlClientProvider>
            <CursorFollower />
            <Header />
            {children}
            <Footer />
            <ScrollToTopButton />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
